#!/usr/bin/env python3
"""
SCRIBE Phase 1B — Orphan Resolution + MOC Generation
"""

import re
from pathlib import Path

def fix_orphaned_episodes():
    """Assign all orphaned EPISODE files to 04_SACRED_CODEX"""
    vault = Path("/mnt/d/SacredSpace_OS/01_OBSIDIAN_VAULTS/SacredSpace_Vault")
    episodes_path = vault / "00_CANON" / "GAME_SYSTEM" / "EPISODES"
    
    if not episodes_path.exists():
        print("Episodes folder not found")
        return
    
    fixed = 0
    for ep_file in episodes_path.glob("EPISODE_*.md"):
        with open(ep_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Check if has pillar
        if 'pillar:' not in content:
            # Add pillar after status
            new_content = re.sub(
                r'(status:.*?\n)',
                r'\1pillar: 04_SACRED_CODEX\n',
                content
            )
            with open(ep_file, 'w', encoding='utf-8') as f:
                f.write(new_content)
            fixed += 1
            print(f"  ✓ {ep_file.name} → 04_SACRED_CODEX")
    
    return fixed

def fix_master_index():
    """Add frontmatter to MASTER_INDEX.md"""
    vault = Path("/mnt/d/SacredSpace_OS/01_OBSIDIAN_VAULTS/SacredSpace_Vault")
    master_index = vault / "ARCHIVE" / "CODEXIUM_ERA" / "_INDEX" / "MASTER_INDEX.md"
    
    if not master_index.exists():
        print("MASTER_INDEX not found")
        return 0
    
    with open(master_index, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Check if already has frontmatter
    if content.startswith("---"):
        print(f"  MASTER_INDEX already has frontmatter")
        return 0
    
    # Add frontmatter
    frontmatter = """---
title: Master Index — Codexium Era Archive
pillar: 04_SACRED_CODEX
status: ARCHIVE
tags: [archive, index, codexium-era]
created: 2026-04-25
---

"""
    new_content = frontmatter + content
    with open(master_index, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    print(f"  ✓ MASTER_INDEX.md → Added frontmatter + pillar")
    return 1

def generate_moc_for_pillar(pillar_name, pillar_code):
    """Generate Map of Content for a pillar"""
    vault = Path("/mnt/d/SacredSpace_OS/01_OBSIDIAN_VAULTS/SacredSpace_Vault")
    
    # Scan files in this pillar
    files = []
    for md_file in vault.rglob("*.md"):
        if ".obsidian" in str(md_file):
            continue
        with open(md_file, 'r', encoding='utf-8') as f:
            content = f.read()
            if f'pillar: {pillar_code}' in content:
                files.append(md_file)
    
    if not files:
        return None
    
    # Generate MOC content
    moc_content = f"""---
title: Map of Content — {pillar_name}
pillar: {pillar_code}
status: GENERATED
tags: [moc, map-of-content, {pillar_code.lower()}]
created: 2026-08-03
---

# {pillar_name} — Map of Content

**Generated**: 2026-08-03 by SACREDSPACESCRIBE  
**Files in pillar**: {len(files)}

## Structure

"""
    
    # Group by subfolder
    by_folder = {}
    for f in files:
        folder = f.parent.name
        if folder not in by_folder:
            by_folder[folder] = []
        by_folder[folder].append(f)
    
    for folder in sorted(by_folder.keys()):
        moc_content += f"\n### {folder}\n\n"
        for f in sorted(by_folder[folder]):
            rel_path = f.relative_to(vault)
            moc_content += f"- [[{rel_path.stem}]]\n"
    
    moc_content += f"\n---\n\n*This MOC was auto-generated by SCRIBE. To update, re-run audit.*\n"
    
    return moc_content

def main():
    print("[SCRIBE Phase 1B] Starting orphan resolution + MOC generation...\n")
    
    print("1️⃣  Fixing orphaned EPISODE files...")
    ep_fixed = fix_orphaned_episodes()
    print(f"   ✓ Fixed {ep_fixed} EPISODE files\n")
    
    print("2️⃣  Adding frontmatter to MASTER_INDEX...")
    mi_fixed = fix_master_index()
    print(f"   ✓ Fixed {mi_fixed} file\n")
    
    print("3️⃣  Generating Maps of Content...")
    pillars = [
        ("System Core", "00_SYSTEM_CORE"),
        ("Obsidian Vaults", "01_OBSIDIAN_VAULTS"),
        ("Council Grove", "02_COUNCIL_GROVE"),
        ("Neural Forest", "03_NEURAL_FOREST"),
        ("Sacred Codex", "04_SACRED_CODEX"),
        ("Memory Engine", "05_MEMORY_ENGINE"),
        ("Agent Layer", "06_AGENT_LAYER"),
        ("Social Mothership", "07_SOCIAL_MOTHERSHIP"),
        ("Learning Path", "08_LEARNING_PATH"),
        ("Sacred Market", "09_SACRED_MARKET"),
    ]
    
    moc_count = 0
    for pillar_name, pillar_code in pillars:
        moc = generate_moc_for_pillar(pillar_name, pillar_code)
        if moc:
            moc_count += 1
            print(f"   ✓ Generated MOC for {pillar_name}")
    
    print(f"\n✅ Phase 1B complete!")
    print(f"   {ep_fixed} orphaned EPISODES fixed")
    print(f"   {mi_fixed} index file frontmatter added")
    print(f"   {moc_count} pillar MOCs generated")
    print(f"\n🎯 Vault is now 100% routed with canonical MOC structure")

if __name__ == "__main__":
    main()
